# Generated by Django 5.0.4 on 2024-04-12 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_app", "0004_influencer_produtos_produto_prod_categoria_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="prod_categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="site_app.categoria"
            ),
        ),
    ]
